apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-node
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: demo-node
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
