apiVersion: v1
kind: Service
metadata:
  name: demo-node
  namespace: default
  labels:
    app: demo-node
spec:
  selector:
    app: demo-node
  ports:
    - name: http
      port: 3000
      targetPort: 3000
